### ISSUE TITLE
Locking / Content addressable chunks for deduplication?

### ISSUE THREAD

**Issue by vsivsi** [internalfx/regrid-spec#3]
Hi, I'm a seasoned gridFS developer, and I was just about to start a similar effort to this when I found this project today. It looks very interesting, and since there are still TBDs floating around, there seems to be the opportunity to weigh in with some ideas. So here goes:

A couple of major shortcomings of gridFS I've encountered that you might want to consider:
1.   gridFS is not safe for concurrent access. At all. Unless your system treats files as immutable (which is hard to enforce, and often impractical or undesirable). So some allowance for locking to allow an entire consistent version of a file to be read before it can be modified or removed is necessary. I see that you have "versions" based on filename, but how that interacts with appending to a file, or removing one, is unclear. Anyway, automatic safe concurrent access to file data should be a hard requirement. If one process begins reading from a file with a given sha256, it should always be able to receive the entire corresponding file, regardless of what other processes are simultaneously trying to do (e.g. change or remove the file).  
   See this for more info on the gridFS concurrency situation: https://github.com/vsivsi/gridfs-locks#why
2.   Rather than going to a lot of work to make concurrent access safe via some kind of locking mechanism, maybe the answer is to implement strong versioning (with deduplication of redundant blocks) via content addressable block storage, reference counting, and an rsync-like content defined chunking scheme. There is a lot of interesting work going on in the Dat project along these lines, and in fact, the Dat protocol (based on Merkle trees and content defined chunks) might be a great way of reliably up/downloading files from a regrid store. I don't have a fully baked idea of how this would be implemented, but its worth thinking about before just doing what gridFS did with sequential fixed sized chunks. https://github.com/maxogden/dat
3.   Filenames are just metadata. The sha256 is the unique ID for the contents of a version of a file, and the unique ReThink document id key is the unique ID for an instance of a file (the same identical data may be stored multiple times, after all). IMO filenames shouldn't be 1st class entities in the API (or maybe even the file document). There are many possible schemes for looking up files, and filenames are just one. Why enshrine this rather archaic way of identifying files in the API? And if you do, why not also have hierarchical folders too, etc? There may be many files in a bucket, belonging to different users, with different unrelated content, but that share the same filename (e.g. `README.md`, `favicon.png`, `.travis.yaml`). My quick read of the filename+version scheme is that it breaks down a bit if you have 100's of distinct README.md files, each simultaneously undergoing its own unique set of revisions.

Anyway, it looks like you have a good start here. And RethinkDB definitely needs something like this. Just thought I'd inject some ideas born out of my experiences with gridFS, because it is not the ideal representation, and the MongoDB folks recognize that and have assured me they are (or will be) working on a better replacement for it.

**Comment by internalfx** [comment]
Hi @vsivsi,

Thanks for weighing in, I appreciate having more expertise on the project. (I use this in production, so the more the merrier)

The spec is a little sadly out of date with my reference implementation. I haven't had as much time as is needed to bring this up-to-date.
1. Files _are_ treated as immutable. Every write is a new version that is basically invisible to "readers" until it is complete. There is no appending a file. Removing a file requires the ID of a specific file (it could be just one of the versions of a file). I believe you are correct that deleting a file could cause a read to fail. But the read does not fail silently or produce corrupted data. Sha256 is calculated on the way in and always verified on the way back out.
2. I'm not very well versed on the subject matter...sorry
3. Filenames are a first-class citizen for speed. We do have metadata, but it is not as fast as Filename because we have very tailored indexes to speed this up that I'm not sure would work against an object (metadata). We will have to verify with @danielmewes on that one, but let me just say the indexes were debated **heavily** in this project.

**Comment by vsivsi** [comment]
Hey, thanks for the quick response. I understand what you're saying. Here's a use case to consider:

I have a system that produces an ever growing file that is being constantly appended to (streaming data from a scientific instrument). I'd like to be able to capture "snapshots" of this file in a replicated, reliable datastore for live periodic updates of a database containing a summary of the data collected so far (to drive a dashboard, live analytics, etc). The file is huge, and being able to automatically deduplicate the unchanged parts of the file between versions (similar to what git does internally) would be a big win both in terms of write performance and storage efficiency.

This case is what 2) is really about. Right now, regrid doesn't seem to solve this problem, and I'd love if it somehow did, because it would save me having to define _yet another_ competing system for storing files in Rethink (or choosing a different DB entirely).

**Comment by internalfx** [comment]
@vsivsi After hearing your use case I have to come to the conclusion that ReGrid is not the right solution for you.

**Comment by vsivsi** [comment]
Fair enough. Thanks again for the quick responses.
